version: "3.7"

services:
  api:
    image: kdo-api:dev
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - 8081:80/tcp
  webui:
    image: kdo-webui:dev
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 8080:80/tcp
    