"""First revision

Revision ID: d4867f3a4c0a
Revises:
Create Date: 2021-12-28 13:53:32.978401

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d4867f3a4c0a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gift",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("buy_price", sa.Float(), nullable=True),
        sa.Column("recipient", sa.String(), nullable=False),
        sa.Column("giver", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gift_recipient"), "gift", ["recipient"], unique=False)
    op.create_index(op.f("ix_gift_giver"), "gift", ["giver"], unique=False)
    op.create_index(op.f("ix_gift_id"), "gift", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gift_id"), table_name="gift")
    op.drop_index(op.f("ix_gift_giver"), table_name="gift")
    op.drop_index(op.f("ix_gift_recipient"), table_name="gift")
    op.drop_table("gift")
    # ### end Alembic commands ###
